on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    - name: Checkout repository
      uses: actions/checkout@v2.5.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - run: npm -g i pnpm
    - name: Install dependencies
      run: pnpm i
    - name: Run tests
      run: pnpm tests
