name: Test

on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Check Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 19

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
